# Generated by Django 2.2.6 on 2019-11-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('update_time', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='课程更新时间')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='课程创建时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255, verbose_name='课程名')),
                ('image_thumb', models.ImageField(height_field='url_height', upload_to='course', verbose_name='课程封面图', width_field='url_width')),
                ('url_width', models.IntegerField(default=500, verbose_name='图片宽度')),
                ('url_height', models.IntegerField(default=500, verbose_name='图片高度')),
                ('video', models.FileField(default=None, upload_to='course/video/', verbose_name='课程视频')),
                ('descriptions', models.TextField(verbose_name='课程简介，这里应该为富文本编辑器的代码')),
                ('start_time', models.DateTimeField(verbose_name='课程开始时间')),
                ('end_time', models.DateTimeField(verbose_name='课程结束时间')),
                ('is_active', models.BooleanField(default=False, verbose_name='课程是否可用')),
                ('course_level', models.CharField(choices=[('6', '小学六年级'), ('7', '初一'), ('8', '初二'), ('5', '小学5年级')], default='6', max_length=100, verbose_name='课程使用年级')),
                ('allow_number', models.IntegerField(default=50, verbose_name='课程允许参加的人数')),
                ('is_full', models.BooleanField(default=False, verbose_name='课程预订是否已满')),
                ('course_subject', models.CharField(choices=[('English', '英语'), ('Math', '数学'), ('Chinese', '语文'), ('Others', '其他')], default='English', max_length=100, verbose_name='课程科目类别')),
                ('course_tag', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='课程左上角角标文字')),
                ('course_price', models.FloatField(default=0, verbose_name='课程价格')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='CourseImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(height_field='url_height', upload_to='course_images', verbose_name='图片地址', width_field='url_width')),
                ('sort', models.IntegerField(default=1, verbose_name='图片排序')),
                ('name', models.CharField(default='图片', max_length=255, verbose_name='图片名称')),
                ('url_width', models.IntegerField(default=500, verbose_name='图片宽度')),
                ('url_height', models.IntegerField(default=500, verbose_name='图片高度')),
            ],
            options={
                'verbose_name': '课程图片',
                'verbose_name_plural': '课程图片',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('update_time', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='课程更新时间')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='课程创建时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(default='题目如下：', max_length=255, verbose_name='问题题目')),
                ('question_name', models.CharField(default='默认题目', max_length=255, null=True, verbose_name='问题名称')),
                ('question_text', models.TextField(blank=True, default=None, null=True, verbose_name='问题文本')),
                ('question_type', models.CharField(choices=[('fill', '填空题'), ('choose', '单选择题'), ('line', '连线题'), ('mark', '标记题'), ('sort', '排序题'), ('text', '作文题'), ('change', '改错题'), ('checkbox', '多选题')], default='fill', max_length=40, verbose_name='问题类型')),
                ('allow_change_index', models.CharField(blank=True, default='', max_length=100, verbose_name='填空题允许交换位置的正确答案的索引')),
                ('question_answer', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='问题答案')),
                ('show_time', models.IntegerField(default=10, verbose_name='问题弹出的时间秒数')),
                ('wait_time', models.IntegerField(default=30, verbose_name='回答问题的时间')),
                ('task_info', models.TextField(blank=True, default=None, null=True, verbose_name='问题具体内容设置')),
                ('mark_type', models.CharField(choices=[('line', '下划线'), ('circle', '圈线')], default='line', max_length=100, verbose_name='标记题型时标记类型')),
                ('image_type', models.BooleanField(default=False, verbose_name='题目中是否存在图片')),
            ],
            options={
                'verbose_name': '课程问题',
                'verbose_name_plural': '课程问题',
                'ordering': ['show_time'],
            },
        ),
        migrations.CreateModel(
            name='QuestionsAnswer',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='提交时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.TextField(verbose_name='学生作答的答案')),
                ('is_right', models.BooleanField(blank=True, default=False, verbose_name='答案是否正确')),
                ('answer_version', models.CharField(blank=True, default='v1', max_length=20, verbose_name='学生答案的版本')),
                ('is_text', models.BooleanField(blank=True, default=False, verbose_name='是否是作文题')),
                ('marked_type', models.BooleanField(blank=True, default=False, verbose_name='作文题老师查看状态')),
                ('answer_score', models.IntegerField(blank=True, default=0, verbose_name='答案分数')),
            ],
            options={
                'verbose_name': '答题记录',
                'verbose_name_plural': '答题记录',
            },
        ),
        migrations.CreateModel(
            name='QuestionsImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(height_field='url_height', upload_to='questions_images', verbose_name='图片地址', width_field='url_width')),
                ('sort', models.IntegerField(default=1, verbose_name='图片排序')),
                ('bind_text', models.CharField(default='', max_length=255, verbose_name='与图片绑定的文本内容')),
                ('url_width', models.IntegerField(default=500, verbose_name='图片宽度')),
                ('url_height', models.IntegerField(default=500, verbose_name='图片高度')),
            ],
            options={
                'verbose_name': '问题图片',
                'verbose_name_plural': '问题图片',
            },
        ),
    ]
