# Generated by Django 2.2.1 on 2019-12-24 18:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('order_number', models.CharField(default='L23MS31OT1577183051375S95738', max_length=100, verbose_name='出库单号')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '入库中'), (3, '完成'), (4, '审核不通过'), (5, '已过期'), (6, '已删除')], default=0, verbose_name='出库单状态')),
                ('important_level', models.PositiveSmallIntegerField(choices=[(1, '低优先级'), (2, '一般'), (3, '高优先级')], default=2, verbose_name='优先级')),
                ('expired_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 23, 18, 24, 11, 374861), null=True, verbose_name='过期时间')),
                ('note', models.TextField(default='', max_length=500, verbose_name='备注')),
                ('order_info', django_mysql.models.JSONField(default='', verbose_name='订单信息')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_order_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_outbound_orders', to='user.Department', verbose_name='出库部门')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_order_operator', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '出库单',
                'ordering': ['-created_at'],
            },
        ),
    ]
