# Generated by Django 2.2.1 on 2019-12-24 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundorder',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 23, 18, 24, 39, 908660), null=True, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='order_number',
            field=models.CharField(default='L30MS40OT1577183079909S39458', max_length=100, verbose_name='出库单号'),
        ),
    ]
