# Generated by Django 2.2.1 on 2019-12-24 15:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0003_auto_20191224_1546'),
        ('material', '0002_auto_20191224_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('task_number', models.CharField(max_length=100, verbose_name='任务编号')),
                ('order_number', models.CharField(max_length=40, unique=True, verbose_name='绑定单号')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '待开始'), (1, '正在进行'), (4, '任务错误'), (3, '完成'), (5, '已过期'), (6, '已删除')], default=0, verbose_name='任务状态')),
                ('task_type', models.PositiveSmallIntegerField(choices=[(1, '入库任务'), (2, '出库任务'), (3, '移库任务'), (4, '盘点任务'), (5, '报表任务')], default=1, verbose_name='任务类型')),
                ('important_level', models.PositiveSmallIntegerField(choices=[(1, '低优先级'), (2, '一般'), (3, '高优先级')], default=2, verbose_name='优先级')),
                ('action', models.PositiveSmallIntegerField(choices=[(1, '放入'), (2, '取出'), (3, '盘点')], default=1, verbose_name='操作类型')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_tasks', to='location.StoreLocation', verbose_name='目标库位')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_tasks', to='material.Material', verbose_name='操作物料')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_operator', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('relation_tasks', models.ManyToManyField(blank=True, related_name='_task_relation_tasks_+', to='inbound.Task', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '库内任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('order_number', models.CharField(max_length=100, verbose_name='入库单号')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '入库中'), (3, '完成'), (4, '审核不通过'), (5, '已过期'), (6, '已删除')], default=0, verbose_name='入库单状态')),
                ('important_level', models.PositiveSmallIntegerField(choices=[(1, '低优先级'), (2, '一般'), (3, '高优先级')], default=2, verbose_name='优先级')),
                ('expired_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 23, 15, 46, 53, 541724), null=True, verbose_name='过期时间')),
                ('note', models.TextField(default='', max_length=500, verbose_name='备注')),
                ('order_info', django_mysql.models.JSONField(default='', verbose_name='订单信息')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_order_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '入库单',
                'ordering': ['-created_at'],
            },
        ),
    ]
