# Generated by Django 2.2.1 on 2019-12-24 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0003_auto_20191224_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundorder',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 23, 18, 24, 39, 906917), null=True, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='inboundorder',
            name='order_number',
            field=models.CharField(default='L12MS12IN1577183079907S32678', max_length=100, verbose_name='入库单号'),
        ),
    ]
