# Generated by Django 2.2.1 on 2019-12-27 20:57

from django.db import migrations, models
import libs.custom_models.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20191224_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storelocation',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='目前最早批次'),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='note',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='store_info',
            field=libs.custom_models.json_field.JSONField(blank=True, default=dict, null=True, verbose_name='库存信息'),
        ),
    ]
