# Generated by Django 2.2.1 on 2019-12-02 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('area_name', models.CharField(default='默认库区', max_length=100, verbose_name='库区名称')),
                ('area_code', models.CharField(default='编码1', max_length=100, verbose_name='库区编码')),
                ('area_type', models.PositiveSmallIntegerField(choices=[(1, '面包线'), (2, '桶装线'), (3, '虚拟区')], default=1, verbose_name='库区类型')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '停用'), (-1, '已删除'), (2, '检修中')], default=1, verbose_name='库区状态')),
                ('note', models.TextField(default='', max_length=500, verbose_name='备注')),
                ('extra_info', django_mysql.models.JSONField(default='', verbose_name='额外信息(JSON数据)')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_operator', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '库区管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
