# Generated by Django 2.2.1 on 2019-12-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storearea',
            name='extra_info',
            field=models.TextField(default='', verbose_name='额外信息(JSON数据)'),
        ),
    ]
