# Generated by Django 2.2.1 on 2019-12-09 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storearea',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='storearea',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_create', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='storearea',
            name='extra_info',
            field=models.TextField(default='', verbose_name='额外信息(JSON数据)'),
        ),
        migrations.AlterField(
            model_name='storearea',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_operate', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
    ]
