# Generated by Django 2.2.1 on 2019-12-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_auto_20191209_2145'),
        ('area', '0002_auto_20191224_1546'),
    ]

    operations = [
    ]
